### ISSUE TITLE
Rename /usr/apis to /usr/lib

### ISSUE THREAD

**Issue by aaronmallen** [lyqyd/cc-packman#48]
IMO if were are going to use `bin` instead of `programs` (bin being a unix standard, programs being how computercraft rom is laid out) then we should be utilizing `lib` instead of `apis`.

**Comment by lyqyd** [comment]
Both of those are already in use by various repos for their packages, though it appears that `/usr/apis` is more widespread. Any package maintainer is welcome to target their files wherever they wish. I personally prefer `apis` within the context of ComputerCraft. If I were to start all over on packman, I'd probably go with `/usr/lib`, but I feel like there's very little point attempting to make that change at this point.

Feel free to use `/usr/lib` for your own libraries, it certainly won't hurt anything!

**Comment by aaronmallen** [comment]
+1

**Comment by aaronmallen** [comment]
I can agree with that... But perhaps have pack an build both to not insinuate a preference towards one or the other... Currently only building the api directory may be building an indirect standardization on how one develops for packman

**Comment by aaronmallen** [comment]
Additionally an etc folder is being built outside the `/usr/` directory... Not sure if this is by design or not.

**Comment by lyqyd** [comment]
Packman currently only creates directories needed for the files installed. If a package places files in the `/usr/lib` directory, it will be created at that time (and deleted, if the package is removed and the folder is otherwise empty, just like any other folder). You're suggesting that `/usr/apis` and `/usr/lib` be treated as special cases, and be created when any packages are installed, and never removed, even when empty. The current behavior is consistent across all files that packman manages. You might be interested in seeing what's left in the file system after telling packman to remove all installed packages, including itself.

`/etc` being created is also intentional, as this is where packman stores the data files that it uses. I suppose best practice would be to have all of its files under `/etc/packman`, but that's another case of hindsight being a bit better than foresight.

**Comment by aaronmallen** [comment]
Cool I am going to go ahead an close this then.
