### ISSUE TITLE
Namespacing Packman Packages

### ISSUE THREAD

**Issue by aaronmallen** [lyqyd/cc-packman#49]
With my current understanding of the way packman `addFile` works if two packages have a file of the same name (i.e. `install`) the latest package installed will override the other.  Perhaps namespacing packages would address this issue.  Ideally all of my packages would be installed in `/usr/bin/aaronmallen/<package file>` but `easy-shell` would still be able to expose the individual programs to the root. Not sure if this issue should be here or on the easy-shell repo...

**Comment by lyqyd** [comment]
It's true that the files would be overwritten, but packages are also installed one at a time, so the installers system you're using will still work fine.

Separate folders per repo would add significantly more to the path string necessary in easy-shell, as well as being *extremely* likely to break one or more packages that expect to end up in `/usr/bin`, since that's their installation target. If you'd prefer to target `/usr/bin/aaronmallen`, you are obviously welcome to do so.

This would be a significant breaking change, so I'm very reluctant to go down this path.

**Comment by aaronmallen** [comment]
Leaving this responsibility to the developer is understandable, closing.
